snickersMarket/urls.py
from django.urls import path

from . import views

app_name = 'snickersMarket'
urlpatterns = [
    # Views for loading webpages to show in browser
    path('', views.index_view, name='index'),  # page for all products ( catalogue )

    # Views for api requests
    path('api/products/', views.products_api, name='api_index'),  # get all products
    path('api/<int:pk>/', views.product_detail_api, name='api_detail'),  # get information of single product
    path('api/bag/', views.bag_api, name='bag'),  # bag apis
    path('api/favourites/', views.favourites_api, name='favourites'),  # favourites apis
    path('api/edit/create_product/', views.create_product_api, name='create_product'),  # create product
    path('api/delete_bag/', views.delete_bag_api, name='delete_bag'),
    path('api/add_favourites/', views.add_favourite_api, name='delete_favourite'),

    # payments
    path('api/payment/', views.payment_api, name='payment'),

    # path('edit/api/can_edit', views.can_edit_api, name='can_edit'),  # check if user can edit product list

    # Get all entries from db
    path('api/entries/<str:value_name>', views.entries_api, name='entries'),

    # logout page ( mostly for debug purposes )
    path('logout/', views.logout_api, name='logout'),

    # page for logining user in
    path('login/', views.login_api, name='login'),
]

tgShop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('snickersMarket.urls')),
]

snickersMarket/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    class Meta:
        permissions = [
            ('edit_products', 'Can edit products list'),
        ]

    name = models.CharField(max_length=100)
    description = models.CharField(max_length=300, blank=True)

    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100, blank=True)

    price = models.IntegerField()

    color = models.CharField(max_length=100)

    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return f'{self.name}'


class Buyer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    favourites = models.ManyToManyField(Product, related_name='favourites+')
    bag = models.ManyToManyField(Product, related_name='bag+')

snickersMarket/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.views.decorators.csrf import ensure_csrf_cookie
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.datastructures import MultiValueDictKeyError
from django.conf import settings
from django.core.exceptions import FieldError

from .models import Product, Buyer
from .serializers import ProductSerializer

from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.renderers import JSONRenderer
from rest_framework import status, generics

from urllib.parse import urlparse, parse_qs  # for login api

import requests
import json


def index_view(request):
    """View for home page, showing all products"""
    template_html = 'index.html'
    return render(request, template_html)


@api_view(['GET'])
def products_api(request):
    """Get list of all products"""
    if request.method == 'GET':
        user_id = request.query_params.get('user_id')

        if user_id is None:
            return Response(status=status.HTTP_400_BAD_REQUEST)

        if user_id != request.user.username:
            logout(request)
            login_func(request, user_id)

        query_params = request.query_params
        if query_params:
            fields = [f.name for f in Product._meta.get_fields()]

            kwargs = {key: value for key, value in query_params.items() if key in fields}

            products = Product.objects.filter(**kwargs)
        else:
            products = Product.objects.all()

        serializer = ProductSerializer(products, many=True, context={'request': request})
        return Response(serializer.data)


@login_required
@api_view(['GET'])
def product_detail_api(request, pk):
    """Get information of single product"""
    if request.method == 'GET':
        product = get_object_or_404(Product, pk=pk)
        serializer = ProductSerializer(product, many=False)
        return Response(serializer.data)


@api_view(['GET'])
def logout_api(request):
    """Log out user"""
    logout(request)

    if request.method == 'GET':
        try:
            next_url = request.GET['next']
            return redirect(next_url)
        except MultiValueDictKeyError:
            return Response(status=status.HTTP_200_OK)


@login_required
@api_view(['GET', 'POST', 'DELETE'])
def bag_api(request):
    if request.method == 'GET':
        """Get request's user's bag and serialize it"""
        user = request.user

        bag = user.buyer.bag.all()
        serializer = ProductSerializer(bag, many=True)
        return Response(serializer.data)

    elif request.method == 'POST':
        """Add product using product's id from data['id'] to bag of user from request"""
        try:
            product_id = request.data['id']
        except KeyError:
            return Response(status=status.HTTP_400_BAD_REQUEST)

        # add product to user's bag
        user = request.user
        product = get_object_or_404(Product, id=product_id)

        if not user.buyer.bag.filter(pk=product.pk).exists():
            user.buyer.bag.add(product)

        return Response(status=status.HTTP_200_OK)


@login_required
@api_view(['POST'])
def delete_bag_api(request):
    if request.method == 'POST':
        """Delete product from user's bag"""
        try:
            product_id = request.data['id']
        except KeyError:
            return Response(status=status.HTTP_400_BAD_REQUEST)

        # delete product from user's bag
        user = request.user
        product = get_object_or_404(Product, id=product_id)

        if user.buyer.bag.filter(pk=product.pk).exists():
            user.buyer.bag.remove(product)
        else:
            return Response(status=status.HTTP_404_NOT_FOUND)

        return Response(status=status.HTTP_200_OK)


@login_required
@api_view(['GET', 'POST', 'DELETE'])
def favourites_api(request):
    if request.method == 'GET':
        """Get request's user's favourite products and serialize them"""
        user = request.user

        favourites = user.buyer.favourites.all()
        serializer = ProductSerializer(favourites, many=True)
        return Response(serializer.data)

    elif request.method == 'POST':
        """Add product using product's id from data['id'] to favourite products list of user from request"""
        try:
            product_id = request.data['id']
        except KeyError:
            return Response(status=status.HTTP_400_BAD_REQUEST)

        # add product to user's bag
        user = request.user
        product = get_object_or_404(Product, id=product_id)
        user.buyer.favourites.add(product)

        return Response(status=status.HTTP_200_OK)

    elif request.method == 'DELETE':
        """Delete product from user's favourite products list"""
        try:
            product_id = request.data['id']
        except KeyError:
            return Response(status=status.HTTP_400_BAD_REQUEST)

        # delete product from user's bag
        user = request.user
        product = get_object_or_404(Product, id=product_id)

        if user.buyer.favourites.filter(pk=product.pk):
            user.buyer.favourites.remove(product)
        else:
            return Response(status=status.HTTP_404_NOT_FOUND)

        return Response(status=status.HTTP_200_OK)


def login_func(request, user_id):
    # Get user using received id
    user = authenticate(request=request, username=user_id, password='')

    # Create user if not present
    if user is None:
        user = User.objects.create_user(username=user_id, password='')
        user.save()

        # connect user with buyer
        Buyer.objects.create(user=user)

    # Log in user
    login(request, user)


@api_view(['GET'])
def login_api(request):
    """Log in user, using id from request url"""
    # Request url with user id is in 'next' key
    try:
        next_url = request.GET['next']
    except MultiValueDictKeyError:
        return Response(status=status.HTTP_400_BAD_REQUEST)  # can't go directly to login api

    # Find user id from received link
    parse_object = urlparse(next_url)
    query = parse_qs(parse_object.query)

    user_id = query.get('user_id')
    if not user_id:
        return Response(status=status.HTTP_400_BAD_REQUEST)  # can't authorize without given id

    user_id = ''.join(user_id)  # get string from list of single string

    login_func(request, user_id)

    return redirect(next_url)


@login_required
@staff_member_required
@api_view(['POST'])
def create_product_api(request):
    """Create product using request"""
    if request.method == 'POST':
        serializer = ProductSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@login_required
@api_view(['POST'])
def add_favourite_api(request):
    if request.method == 'POST':
        serializer = ProductSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


# @login_required
# @api_view(['GET'])
# def can_edit_api(request):
#     result = str(request.user.has_perm('snickersMarket.add_product'))
#     return HttpResponse({'result': result})
#     # return Response({'result': result})


@login_required
@api_view(['GET'])
def entries_api(request, value_name):
    """Get all variant of values in Product 'value_name' field"""
    if request.method == 'GET':
        try:
            all_entries = Product.objects.order_by().values(value_name).distinct()
        except FieldError:
            return Response(status=status.HTTP_400_BAD_REQUEST)

        return Response(all_entries)


@login_required
@api_view(['GET'])
def payment_api(request):
    if request.method == 'GET':
        # get tokens
        with open('/home/git/tgShop/work/BOT_TG/config.py') as cf:
            for line in cf:
                if line.startswith('BOT_TOKEN'):
                    bot_token = line.split()[-1].replace('\'', '')
                if line.startswith('PAYMENTS_PROVIDER_TOKEN'):
                    payment_token = line.split()[-1].replace('\'', '')

        # get all objects (array of labeledPrice)
        prices = []
        user = request.user
        products = user.buyer.bag.all()
        for product in products:
            prices.append({
                'label': product.name,
                'amount': product.price * 100,
            })

        # get url for requesting link
        url = f'https://api.telegram.org/bot{bot_token}/createInvoiceLink'

        # get dictionary for requesting link
        cil_json = {
            'title': 'Order #',
            'description': 'test description',
            'provider_token': payment_token,
            'currency': 'RUB',
            'prices': prices,
            'payload': {
                'order': 1  # TODO make order id
            }
        }

        request = requests.post(url=url, json=cil_json)
        request_dict = json.loads(request.text)

        with open('/home/git/testInvoice.txt', 'w') as fd:
            fd.write(str(request_dict) + '\n')
            fd.write(f'url{str(url)}\njson{cil_json}\n')

        try:
            link = request_dict['result']
        except KeyError:
            return Response(status=status.HTTP_404_NOT_FOUND)

        return Response(link)

snickersMarket/templates/snickersMarket/bag.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bag page</title>
</head>
<body>
    <div id="bag">
        {% verbatim %}
            <div class="element" v-for="(element, id) in elements" :key="element.id">

                <a :href="getUrl(element.id)">{{ element.name }}</a>

                <p>
                    {{ element.product }}: amount: {{ element.amount }}, color: {{ element.color }}, size: {{ element.size }}
                </p>

            </div>
        {% endverbatim %}
    </div>

    <script>
        const urlRoot = '{% url 'snickersMarket:index' %}'
    </script>

    {% load static %}
    <script src="https://cdn.jsdelivr.net/npm/vue@2.7.8/dist/vue.js"></script>
    <script src={% static "bag.js" %}></script>
</body>
</html>

snickersMarket/templates/snickersMarket/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Product page</title>
</head>
<body>
{% load static %}

<h1>{{ product }}</h1>
<p>Description: {{ product.description }}</p>
<p>Left in stock: {{ product.in_stock }}</p>
<p>Manufacturer: {{ product.manufacturer }}</p>
<img src='/{{ product.image }}' alt="Picture here">

</body>
</html>

snickersMarket/templates/snickersMarket/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create page</title>
</head>
<body>

<form action="/edit/api/create_product/" method="post">
    {% csrf_token %}

    <div>
        <input name="name" id="name" value="Simple shoes">
        <label for="name">Name here</label>
    </div>

    <div>
        <textarea name="description" id="description"></textarea>
        <label for="description">Write description for product</label>
    </div>

    <div>
        <input name="in_stock" id="in_stock" value="10">
        <label for="in_stock">How much left?</label>
    </div>

    <div>
        <input name="price" id="price" value="200">
        <label for="price">How much cost?</label>
    </div>

    <div>
        <input name="manufacturer" id="manufacturer" value="man">
        <label for="manufacturer">Who created it?</label>
    </div>

    <div>
        <button>Create product</button>
    </div>

</form>

</body>
</html>

snickersMarket/templates/snickersMarket/game.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<style>
canvas {
    border:1px solid #d3d3d3;
    background-color: #f1f1f1;
}
</style>
</head>
<body onload="startGame()">
<script>

var myGamePiece;
var myObstacles = [];
var myScore;

function startGame() {
    myGamePiece = new component(30, 30, "red", 10, 120);
    myGamePiece.gravity = 0.05;
    myScore = new component("30px", "Consolas", "black", 280, 40, "text");
    myGameArea.start();
}

var myGameArea = {
    canvas : document.createElement("canvas"),
    start : function() {
        this.canvas.width = 480;
        this.canvas.height = 270;
        this.context = this.canvas.getContext("2d");
        document.body.insertBefore(this.canvas, document.body.childNodes[0]);
        this.frameNo = 0;
        this.interval = setInterval(updateGameArea, 20);
        },
    clear : function() {
        this.context.clearRect(0, 0, this.canvas.width, this.canvas.height);
    }
}

function component(width, height, color, x, y, type) {
    this.type = type;
    this.score = 0;
    this.width = width;
    this.height = height;
    this.speedX = 0;
    this.speedY = 0;
    this.x = x;
    this.y = y;
    this.gravity = 0;
    this.gravitySpeed = 0;
    this.update = function() {
        ctx = myGameArea.context;
        if (this.type == "text") {
            ctx.font = this.width + " " + this.height;
            ctx.fillStyle = color;
            ctx.fillText(this.text, this.x, this.y);
        } else {
            ctx.fillStyle = color;
            ctx.fillRect(this.x, this.y, this.width, this.height);
        }
    }
    this.newPos = function() {
        this.gravitySpeed += this.gravity;
        this.x += this.speedX;
        this.y += this.speedY + this.gravitySpeed;
        this.hitBottom();
    }
    this.hitBottom = function() {
        var rockbottom = myGameArea.canvas.height - this.height;
        if (this.y > rockbottom) {
            this.y = rockbottom;
            this.gravitySpeed = 0;
        }
    }
    this.crashWith = function(otherobj) {
        var myleft = this.x;
        var myright = this.x + (this.width);
        var mytop = this.y;
        var mybottom = this.y + (this.height);
        var otherleft = otherobj.x;
        var otherright = otherobj.x + (otherobj.width);
        var othertop = otherobj.y;
        var otherbottom = otherobj.y + (otherobj.height);
        var crash = true;
        if ((mybottom < othertop) || (mytop > otherbottom) || (myright < otherleft) || (myleft > otherright)) {
            crash = false;
        }
        return crash;
    }
}

function updateGameArea() {
    var x, height, gap, minHeight, maxHeight, minGap, maxGap;
    for (i = 0; i < myObstacles.length; i += 1) {
        if (myGamePiece.crashWith(myObstacles[i])) {
            return;
        }
    }
    myGameArea.clear();
    myGameArea.frameNo += 1;
    if (myGameArea.frameNo == 1 || everyinterval(150)) {
        x = myGameArea.canvas.width;
        minHeight = 20;
        maxHeight = 200;
        height = Math.floor(Math.random()*(maxHeight-minHeight+1)+minHeight);
        minGap = 50;
        maxGap = 200;
        gap = Math.floor(Math.random()*(maxGap-minGap+1)+minGap);
        myObstacles.push(new component(10, height, "green", x, 0));
        myObstacles.push(new component(10, x - height - gap, "green", x, height + gap));
    }
    for (i = 0; i < myObstacles.length; i += 1) {
        myObstacles[i].x += -1;
        myObstacles[i].update();
    }
    myScore.text="SCORE: " + myGameArea.frameNo;
    myScore.update();
    myGamePiece.newPos();
    myGamePiece.update();
}

function everyinterval(n) {
    if ((myGameArea.frameNo / n) % 1 == 0) {return true;}
    return false;
}

function accelerate(n) {
    myGamePiece.gravity = n;
}
</script>
<br>
<button onmousedown="accelerate(-0.2)" onmouseup="accelerate(0.05)">ACCELERATE</button>
<a href="https://youtu.be/EV5vjsUJqgE">Всем привет, здравствуйте</a>

<iframe width="560" height="315" src="https://www.youtube.com/embed/tYlGIESr7nE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</body>
</html>

snickersMarket/templates/snickersMarket/index.html
<!DOCTYPE html>
<html lang="ru" xmlns="http://www.w3.org/1999/html">
{%load static%}

<head>
    <meta charset="UTF-8">
    <title>tgShop</title>
    <link rel="stylesheet" type="text/css" href={%static "style.css"%}>
</head>
<body>

<header>
    <div id="inputWrapper">
        <p>SneackersShop</p>
        <input id="input" type="search" autocomplete="off" spellcheck="false" role="combobox" placeholder="Введите название продукта">
    </div>
</header>



<div id="app" class="app" style="margin-top: 60px; margin-bottom: 9vh">
    <div id="MenuPanel">
        {% verbatim %}
        <button v-for="tab in tabs"
                v-bind:key="tab"
                v-bind:class="['tab-button', {active: currentTab === tab}]"
                v-bind:id="tab"
                v-on:click="currentTab = tab">
            {{ tab }}
        </button>
        {% endverbatim %}
    </div>
    <component v-bind:is="currentTabComponent" class="tab"></component>
</div>

<script src="https://cdn.jsdelivr.net/npm/vue@2.7.8/dist/vue.js"></script>
<script src={%static "app.js"%}></script>
</body>
</html>

snickersMarket/templates/snickersMarket/producttypes.html
<!DOCTYPE html>
<html lang="ru" xmlns="http://www.w3.org/1999/html">
{%load static%}

<head>
  <meta charset="UTF-8">
  <title>tgShop</title>
  <link rel="stylesheet" type="text/css" href={%static "style.css"%}>
</head>
<body>

<header>
  <div id="inputWrapper">
    <p>SneackersShop</p>
    <input id="input" type="search" autocomplete="off" spellcheck="false" role="combobox" placeholder="Введите название продукта">
  </div>
</header>


<div id="app" class="app" style="margin-top: 60px; margin-bottom: 9vh">
  <div id="MenuPanel">
    {% verbatim %}
    <button v-for="tab in tabs"
            v-bind:key="tab"
            v-bind:class="['tab-button', {active: currentTab === tab}]"
            v-bind:id="tab"
            v-on:click="currentTab = tab">
      {{ tab }}
    </button>
    {% endverbatim %}
  </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/vue@2.7.8/dist/vue.js"></script>
<script src="app.js"></script>
<script src="CBF.js"></script>
</body>
</html>

snickersMarket/templates/snickersMarket/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Result page</title>
</head>
<body>

<h1>{{ question.question.page }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

</body>
</html>